# Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
# Q1. Is there any difference in the data type of variables list_ and array_list?
# Print the data types of both variables.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
# Q2. Print the data type of each and every element of both variables list_ and array_list.

for item in list_:
    print("Data type of element in list_:", type(item))

for item in array_list:
    print("Data type of element in array_list:", type(item))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [3]:
# Q3. Change the data type of elements in array_list to int and print the data types of each element.

array_list = np.array(object=list_, dtype=int)

for item in array_list:
    print("Data type of element in array_list (after conversion to int):", type(item))

Data type of element in array_list (after conversion to int): <class 'numpy.int64'>
Data type of element in array_list (after conversion to int): <class 'numpy.int64'>
Data type of element in array_list (after conversion to int): <class 'numpy.int64'>
Data type of element in array_list (after conversion to int): <class 'numpy.int64'>
Data type of element in array_list (after conversion to int): <class 'numpy.int64'>


# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
# Q4. Find the shape and size of the variable num_array.

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
# Q5. Create a numpy array of zeros with shape (3,3).

zeros_array = np.zeros((3, 3))
print("Zeros array:\n", zeros_array)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:

# Q6. Create an identity matrix of shape (5,5).

identity_matrix = np.identity(5)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
